sudo: required
services:
  - docker

before_install:
  - docker build -t ahmedashfaq027/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ahmedashfaq027/react-test npm test -- --coverage

after_success:
  - docker build -t ahmedashfaq027/multi-client ./client
  - docker build -t ahmedashfaq027/multi-nginx ./nginx
  - docker build -t ahmedashfaq027/multi-server ./server
  - docker build -t ahmedashfaq027/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push ahmedashfaq027/multi-client
  - docker push ahmedashfaq027/multi-nginx
  - docker push ahmedashfaq027/multi-server
  - docker push ahmedashfaq027/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-dockers
  env: MultiDockers-env
  bucket_name: elasticbeanstalk-us-west-1-017280410636
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
